- name: Install zsh
  community.general.homebrew:
    name:
      - zsh
      - zsh-completions

- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "{{ ohmyzsh_dir }}"
  register: ohmyzsh_dir_stat

- name: Install oh-my-zsh
  ansible.builtin.command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_dir_stat.stat.exists

- name: Download oh-my-zsh theme
  ansible.builtin.git:
    repo: "{{ ohmyzsh_theme_repo }}"
    dest: "{{ ohmyzsh_theme_dir }}"

- name: Link oh-my-zsh theme
  ansible.builtin.file:
    path: "{{ ohmyzsh_dir }}/custom/themes/r3nic1e.zsh-theme"
    state: link
    src: "{{ ohmyzsh_theme_dir }}/r3nic1e.zsh-theme"

- name: Download oh-my-zsh plugins
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: "{{ ohmyzsh_dir }}/custom/plugins/{{ item.key }}"
    update: false
    accept_newhostkey: true
  with_dict: "{{ ohmyzsh_plugins }}"

- name: Copy .zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_user_dir }}/.zshrc"