- name: Install git
  community.general.homebrew:
    name:
      - git
      - git-filter-repo
      - git-lfs

- name: Copy partial gitconfigs
  ansible.builtin.template:
    src: "gitconfig.{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.gitconfig.{{ item }}"
    mode: 0o600
  with_items: "{{ git_configs | dict2items | map(attribute='value') }}"

- name: Copy main gitconfig
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    mode: 0o600
